name: beima

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LocalMongoConnection: mongodb://localhost:27017
  CurrentEnv: dev-cloud
  DatabaseName: beima
  DeviceCollectionName: devices
  AzureCosmosConnection: ${{ secrets.AZURE_COSMOS_CONNECTION }}
  AzureStorageConnection: ${{ secrets.AZURE_STORAGE_CONNECTION }}
  AzureContainer: "test-files"
  DeviceTypeCollectionName: deviceTypes
  BuildingCollectionName: buildings
  REACT_APP_API_URL: http://localhost:7071/api/
  Host: '{ "CORS" : "*"}'
  MinioAccessKey: "minioadmin"
  MinioSecretKey: "minioadmin"
  MinioBucket: "test-files"

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the build and test scripts
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
            name: cypress-snapshots
            path: BEIMA.Client/cypress/screenshots
